export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';
export const FETCH_USER_DATA_START = 'FETCH_USER_DATA_START';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const SET_TOPICS = 'SET_TOPICS';
export const SET_USER_DATA = 'SET_USER_DATA';
