export const SET_USER_DATA = "SET_USER_DATA";
export const FETCH_USER_DATA_FAILURE = "FETCH_USER_DATA_FAILURE";
export const FETCH_USER_DATA_START = "FETCH_USER_DATA_START";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
